### PR TITLE
Corrected issues noted by Anna-Myzukina from the TSE. 

### PR DESCRIPTION
**Pull request by dannisonarias**
We had some trouble with the Stickler linter. Also, some images appeared broken when the project was viewed from GitHack, but not in our local browsers, so we weren't able to find where the bug was in our computers.

The linter also broke the git flow at one point, because it suggested a branch merge in order to implement all the CSS corrections, but that merged our feature branch with main, which was not supposed to happen. However, Danny was able to revert the merge.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: good!
But not all changes from previous review are implemented:
* [ ] Dislike button is still not displaying.
* [ ] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Here few things things you need to understand for future projects:
* No need to create new Pull request when you submit project for rereview. Just push new changes and submit link to the same pull request.
* You should not merge to master until TSE approves Pull request.    

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work team! :rocket: 
Please consider my following comments, make appropriate corrections and request another review :smile: 

#### Stickler
Please note that this project does not require the use of stickler to lint your project, however, if you must including it, please make sure there are no errors unfixed.

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can.
screenshot

#### Descriptive Readme
Your Readme file will benefit from a workup. When you start to apply to jobs, potential employers will go through your Github account to see the way you work and may form an opinion of the kind of developer you are from what they see. As such, it is important to ensure that all your repositories look very neat and professional. That being said, please consider this [example](https://github.com/Oluwadamilareolusakin/show-junkie-frontend/blob/master/README.md) as what your Readme File should look like! :smile: 

#### Live link
Please remember to update the live link in your project to point to the actual website. My go-to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+1: 

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by HeflerDev** [comment]
Take care with conflicting files and avoid force push.
It is recommended you two announce to each other when working on the repository.

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @dannisonarias @voscarmv  , 👋 You have done a great job in this project 👏 
> Don't forget to add a descriptive description for pull request



----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Pull request merged**
